Bug 1753742 - Update schema for DNSSEC interference study ping to include data for additional queries
mozilla-services/mozilla-pipeline-schemas pull request #719
Opened 2022-02-04 20:53 UTC by ahounsel

Checklist for reviewer:

- [ ] Commits should reference a bug or github issue, if relevant (if a bug is referenced, the pull request should include the bug number in the title)
- [ ] If adding a new field, the field should have a description (see #576 for an example)

For glean changes:
- [ ] Update `templates/include/glean/CHANGELOG.md`

For modifications to schemas in restricted namespaces (see [`CODEOWNERS`](/CODEOWNERS)):
- [ ] Follow the [change control procedure](https://docs.google.com/document/d/1TTJi4ht7NuzX6BPG_KTr6omaZg70cEpxe9xlpfnHj9k/edit#heading=h.ttegrcfy18ck)

2022-02-07 21:03 UTC, jklukas commented
If you rebase this on `main`, it should pass tests since #722 is now merged.

2022-02-07 23:47 UTC, ahounsel commented
Looks like the CI is still failing: https://app.circleci.com/pipelines/github/mozilla-services/mozilla-pipeline-schemas/2713/workflows/cb62c298-e1ca-4fa6-b08a-a73e93415ca2/jobs/5291

2022-02-08 14:11 UTC, jklukas requested changes
Some missing commas in test cases. If you get those fixed up, then CI should pass and we can merge.

2022-02-08 14:11 UTC, jklukas commented on validation/telemetry/dnssec-study-v1.4.dnsresponses.pass.json
> +      "tcpNEWFOUR": [1, 2, 3]
```suggestion
      "udpNEWTWO": [1, 2, 3],
      "tcpNEWTWO": [1, 2, 3],
      "udpNEWTHREE": [1, 2, 3],
      "tcpNEWTHREE": [1, 2, 3],
      "udpNEWFOUR": [1, 2, 3],
      "tcpNEWFOUR": [1, 2, 3]
```

The current CI tests failures are legitimate, and due to these missing commas in this test case.

2022-02-08 14:11 UTC, jklukas commented on validation/telemetry/dnssec-study-v1.4.dnsresponses.pass.json
> +      "udpNEWTHREE": 1,
```suggestion
      "tcpNEWTWO": 1,
      "udpNEWTHREE": 1,
```

2022-02-08 15:53 UTC, ahounsel commented
Does this look like an issue on my end? https://app.circleci.com/pipelines/github/mozilla-services/mozilla-pipeline-schemas/2717/workflows/bac1997b-7241-4483-8e7c-4593026ae138/jobs/5298

2022-02-08 16:39 UTC, jklukas commented
> the post-artifacts stage fails

This is due to lack of creds since this is a PR from a fork. I will retrigger now with creds and this should be able to complete.

2022-02-08 16:53 UTC, jklukas approved these changes

2022-02-08 16:53 UTC, merged