Bug 1901263: Add `profileGroupId` to schemas.
mozilla-services/mozilla-pipeline-schemas pull request #822
Opened 2024-07-18 15:24 UTC by Mossop

This adds the `profileGroupId` being added to the client side in bug 1901263 to the schemas wherever the `clientId` is present. I believe that every ping including `clientId` will include `profileGroupId` however since the new property is not marked as required in any schema (as it cannot be to avoid breaking older versions of Firefox) if new pings are introduced that do not include the property then it should not break anything.

Checklist for reviewer:

- [ ] Commits should reference a bug or github issue, if relevant (if a bug is referenced, the pull request should include the bug number in the title)
- [ ] If adding a new field, the field should have a description (see #576 for an example)
- [ ] If coming from a fork, run integration tests: `./.github/push-to-trigger-integration <username>:<branchname>`

For glean changes:
- [ ] Update `templates/include/glean/CHANGELOG.md`

For modifications to schemas in restricted namespaces (see [`CODEOWNERS`](/CODEOWNERS)):
- [ ] Follow the [change control procedure](https://docs.google.com/document/d/1TTJi4ht7NuzX6BPG_KTr6omaZg70cEpxe9xlpfnHj9k/edit#heading=h.ttegrcfy18ck)

2024-07-18 15:38 UTC, Mossop commented
I'm unsure what the failing test is about, I was seeing that locally too both with and without my change.

2024-07-24 12:16 UTC, akkomar requested changes
This changes the template, but misses rendered schemas. Can you also rebuild schemas following https://github.com/mozilla-services/mozilla-pipeline-schemas?tab=readme-ov-file#adding-a-new-schema?

2024-07-24 13:41 UTC, Mossop commented
> This changes the template, but misses rendered schemas. Can you also rebuild schemas following https://github.com/mozilla-services/mozilla-pipeline-schemas?tab=readme-ov-file#adding-a-new-schema?

Done, and added to the validations. I'm completely unable to run tests for some reason though so I'm not sure if they are passing.

2024-07-24 16:58 UTC, akkomar commented
> Done, and added to the validations. I'm completely unable to run tests for some reason though so I'm not sure if they are passing.

Thank you. Integration tests [do not run for forked PRs](https://github.com/mozilla-services/mozilla-pipeline-schemas?tab=readme-ov-file#packaging-and-integration-tests-optional), I'm triggering it manually here.

There was an issue with dependencies causing tests to fail that I just fixed in https://github.com/mozilla-services/mozilla-pipeline-schemas/pull/823. Can you rebase this PR on the latest `main`?

2024-07-25 09:29 UTC, Mossop commented
Ok rebasing and switching to Linux allowed me to run the tests locally and they passed

2024-07-25 10:04 UTC, akkomar commented
Thank you, this is ready to be merged now.

@chutten just to double check since you seem to have been involved in the implementation - is this schema change good to be merged and land in BQ now?

2024-07-25 10:05 UTC, akkomar approved these changes

2024-07-25 16:21 UTC, chutten approved these changes
> @chutten just to double check since you seem to have been involved in the implementation - is this schema change good to be merged and land in BQ now?

Adding an optional field sounds safe, and the client-side changes are lined up and ready to land as this does. So from my POV it seems good to merge.

2024-07-25 16:43 UTC, merged

2024-07-25 16:48 UTC, Mossop commented
Thanks, how long does it take for this to go to prod, or rather when can I land the client side pieces?

2024-07-25 17:06 UTC, akkomar commented
This change should land in BigQuery tomorrow.
You do not need to wait with client side pieces. Since `additionalProperties` are not set to false in https://github.com/mozilla-services/mozilla-pipeline-schemas/blob/main/schemas/telemetry/main/main.4.schema.json#L25, ping with this new field would pass validation and its value would end up in `additionalProperties` in BQ table.